export const products = [
  {
    id: 1,
    name: "Laptop Pro 14",
    category: "electronics",
    price: 4999,
    rating: 4.8,
    description: "Lekki laptop do pracy, nauki i programowania.",
  },
  {
    id: 2,
    name: "Monitor 27 cali",
    category: "electronics",
    price: 1299,
    rating: 4.6,
    description: "Duży monitor z wysoką rozdzielczością do biura.",
  },
  {
    id: 3,
    name: "Klawiatura mechaniczna",
    category: "accessories",
    price: 349,
    rating: 4.7,
    description: "Wygodna klawiatura mechaniczna z podświetleniem.",
  },
  {
    id: 4,
    name: "Mysz bezprzewodowa",
    category: "accessories",
    price: 159,
    rating: 4.4,
    description: "Ergonomiczna mysz do codziennej pracy.",
  },
  {
    id: 5,
    name: "Fotel biurowy",
    category: "office",
    price: 899,
    rating: 4.5,
    description: "Regulowany fotel do długiej pracy przy komputerze.",
  },
  {
    id: 6,
    name: "Biurko regulowane",
    category: "office",
    price: 1499,
    rating: 4.9,
    description: "Biurko z regulacją wysokości do pracy siedzącej i stojącej.",
  },
  {
    id: 7,
    name: "Słuchawki Bluetooth",
    category: "accessories",
    price: 429,
    rating: 4.3,
    description: "Bezprzewodowe słuchawki z redukcją hałasu.",
  },
  {
    id: 8,
    name: "Tablet 11 cali",
    category: "electronics",
    price: 2399,
    rating: 4.6,
    description: "Tablet do notatek, filmów i lekkiej pracy.",
  },
];